### ISSUE TITLE
[Feature Request] Pure 64 bit image

### ISSUE THREAD

**Issue by kaiomatico** [sakaki-/raspbian-nspawn-64#5]
Hi, first of all thank you for your awesome work. I've compiled the PPSSPP emulator in the 64 bit container and then launched it, but because of errors concerning llvmpipe it crashed as soon as 3d graphics should be rendered. I guess this is a limitation of not having full GPU access when running inside a container. So my question is: could you please create a pure 64 bit kernel AND userland raspbian(or plain debian) image? That would be great! :+1:

**Comment by sakaki-** [comment]
31 Oct 2020: sadly, due to legal obligations arising from a recent change in my 'real world' job, I must announce I am **standing down as maintainer of this project with immediate effect**. For the meantime, I will leave the repo up (for historical interest, and since the Debian package is still in the official Raspbian repos); however, there will be no further updates to the underlying OS images etc., nor will I be accepting / actioning further pull requests or bug reports from this point. Email requests for support will also have to be politely declined, so, **please treat this as an effective EOL notice**.<br><br>For further details, please see my post [here](https://www.raspberrypi.org/forums/viewtopic.php?p=1750206#p1750206).<br><br>With sincere apologies, sakaki ><
